### ISSUE TITLE
Orebfuscator config isn't great with deepslate

### ISSUE THREAD

**Issue by wingzero54** [CivMC/CivDocker#38]
Orebfuscator is generally configured to handle stone and proximity replaces valuables with stone, but this isn't very helpful if you are below 0 and it is surrounded by deepslate.

**Comment by awoo-civ** [comment]
It's poor behavior in general. Also applies to sand, dirt, gravel. Any other block commonly encountered undergroud, really.

Would it be feasible to have the obfuscation logic be "use the material of the block above if it's one of (stone, deepslate, etc.) or else air"?

**Comment by ProgrammerDan** [comment]
would be a great feature request on the Imprex guys fork of the orebfuscator repo.

**Comment by Aleksey-Terzi** [comment]
> Would it be feasible to have the obfuscation logic be "use the material of the block above if it's one of (stone, deepslate, etc.) or else air"?

Not sure about this.
This logic could work for regular obfuscation but for proximity hider it will be looking strange if the player walks forward, sees empty space and unexpectedly will appear many blocks.

What about to make possibility to specify multiple configurations per world depending on Y?

Like:
```
proximity:
  proximity-overworld-above-0:
    enabled: true
    minY: 1
    maxY: 150
...
  proximity-overworld-below-0:
    enabled: true
    minY: -64
    maxY: 0
...
```
